set listchars=tab:--,trail:~,extends:>,precedes:<,nbsp:.
set list

set guioptions=         " Empty guioptions to avoid annoying toolbar
set guioptions+=a       " Auto-select
set guioptions+=c       " Console-like dialog
set guioptions+=i       " Set windows icon

winpos 0 0
set lines=80
set columns=280

colorscheme solarized
