# LS
alias ll='ls -lh'
alias la='ls -lhA'
alias l='ls -CF'

# Pserve
alias pserve='[ -f development-local.ini ] && \
    paster serve --reload development-local.ini || \
    paster serve --reload development.ini ; \
    notify-send --expire-time=500 --hint=int:transient:1 "pserve error" $PWD'

alias rdesktop='rdesktop -u test -p test -g 1280x720'

# ALIASES
alias ipy='ipython'
alias m='imapcli'

alias backup_phone='./backup_restore_profile.sh -b'

alias fuck='sudo $(history -p \!\!)' 

alias nasatv='vlc http://nasatv-lh.akamaihd.net/i/NASA_101@319270/master.m3u8'
